apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
  labels:
    app: mernbackend
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: mernbackend
  template:
    metadata:
      labels:
        app: mernbackend
    spec: 
      containers:
      - name: mernbackend
        image: mernbackend
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: mernbackend
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 5000